- name : "add node js from source "
  become : true
  shell : | 
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash - 

- name : "install node js"
  become : true
  apt : 
    name : ["node.js"]
    state : latest 
    update_cashe : yes  

- name : "install PM2 Globally"
  npm :
    name : pm2 
    global : yes 
